---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: node4
  user: root

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: webservers
  user: yes

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  sudo: yes

  roles:
    - db
